### PR TITLE
Fixed solr filter 

### PR DESCRIPTION
**Pull request by nyeholt**
Allows filtering by either fixed or current-page values to restrict result set based on keywords of the currently viewed page

### CODE REVIEW

**Comment by nyeholt** [comment]
Oh great, lern2branch Marcus...

**Comment by silbinarywolf** [comment]
Please add a class_exists check for MultiValueField on SolrFields. I dont want that module to be a required dependency. Otherwise, all good to PR

**Comment by nyeholt** [comment]
It's a dependency of solr already, which is being checked for.

**Comment by silbinarywolf** [comment]
Ah didnt think of thst. Accepted :)

**Pull request merged**
